//! FIR filter implementation with windowing functions

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::traits::{FilterFloat, lit};
use ndarray::Array1;
use std::fmt;

mod design;
mod fir_filter_type;
mod misc;
#[cfg(test)]
mod tests;
mod types;
mod window_type;

pub use fir_filter_type::*;
pub use types::*;
pub use window_type::*;

use design::design_fir_bandpass;
use design::design_fir_bandstop;
use design::design_fir_highpass;
use design::design_fir_lowpass;

/// Represents a single FIR filter.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(bound = "")]
pub struct Fir<T: FilterFloat = f64> {
    /// The type of filter
    pub filter_type: FirFilterType,
    /// Filter coefficients (taps)
    coeffs: Vec<T>,
    /// Sample rate in Hz
    pub srate: T,
    /// Cutoff frequency (or lower cutoff for bandpass/bandstop) in Hz
    pub freq: T,
    /// Upper cutoff frequency (for bandpass/bandstop) in Hz
    pub freq_upper: Option<T>,
    /// Window type used
    pub window: WindowType,
    /// Kaiser window beta parameter (if applicable)
    pub kaiser_beta: T,
    /// Doubled circular buffer for filter state. The upper half always holds a
    /// contiguous window of the last `n_taps` samples, so the convolution can be
    /// computed as a single slice dot-product without per-tap modulo indexing.
    state: Vec<T>,
    /// Current position in the circular buffer
    state_pos: usize,
    /// Whether the coefficients are symmetric, enabling the half-multiply fast path.
    #[serde(skip)]
    symmetric: bool,
}

impl<T: FilterFloat> Fir<T> {
    /// Creates a new FIR filter with custom coefficients.
    ///
    /// # Arguments
    /// * `coeffs` - Filter coefficients (taps)
    /// * `srate` - Sample rate in Hz
    ///
    /// # Panics
    /// Panics in debug mode if:
    /// - `coeffs` is empty
    /// - `srate` is not positive
    pub fn new_custom(coeffs: Vec<T>, srate: T) -> Self {
        debug_assert!(!coeffs.is_empty(), "FIR filter must have at least one tap");
        debug_assert!(srate > T::zero(), "Sample rate must be positive");

        let n_taps = coeffs.len();
        let symmetric = Self::coeffs_are_symmetric(&coeffs);
        Fir {
            filter_type: FirFilterType::Custom,
            coeffs,
            srate,
            freq: T::zero(),
            freq_upper: None,
            window: WindowType::Rectangular,
            kaiser_beta: T::zero(),
            state: vec![T::zero(); 2 * n_taps],
            state_pos: n_taps,
            symmetric,
        }
    }

    /// Creates a lowpass FIR filter using the windowed-sinc method.
    ///
    /// # Arguments
    /// * `n_taps` - Number of filter taps (must be odd)
    /// * `cutoff` - Cutoff frequency in Hz
    /// * `srate` - Sample rate in Hz
    /// * `window` - Window function to use
    /// * `kaiser_beta` - Beta parameter for Kaiser window (ignored for other windows)
    ///
    /// # Panics
    /// Panics in debug mode if:
    /// - `n_taps` is zero
    /// - `srate` is not positive
    /// - `cutoff` is not positive or >= Nyquist frequency (srate/2)
    pub fn lowpass(n_taps: usize, cutoff: T, srate: T, window: WindowType, kaiser_beta: T) -> Self {
        debug_assert!(n_taps > 0, "Number of taps must be positive");
        debug_assert!(srate > T::zero(), "Sample rate must be positive");
        debug_assert!(
            cutoff > T::zero() && cutoff < srate / lit(2.0),
            "Cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            cutoff
        );

        let coeffs = design_fir_lowpass(n_taps, cutoff, srate, window, kaiser_beta);
        let n = coeffs.len();
        let symmetric = Self::coeffs_are_symmetric(&coeffs);
        Fir {
            filter_type: FirFilterType::Lowpass,
            coeffs,
            srate,
            freq: cutoff,
            freq_upper: None,
            window,
            kaiser_beta,
            state: vec![T::zero(); 2 * n],
            state_pos: n,
            symmetric,
        }
    }

    /// Creates a highpass FIR filter using spectral inversion of a lowpass filter.
    ///
    /// # Arguments
    /// * `n_taps` - Number of filter taps (must be odd)
    /// * `cutoff` - Cutoff frequency in Hz
    /// * `srate` - Sample rate in Hz
    /// * `window` - Window function to use
    /// * `kaiser_beta` - Beta parameter for Kaiser window (ignored for other windows)
    ///
    /// # Panics
    /// Panics in debug mode if:
    /// - `n_taps` is zero
    /// - `srate` is not positive
    /// - `cutoff` is not positive or >= Nyquist frequency (srate/2)
    pub fn highpass(
        n_taps: usize,
        cutoff: T,
        srate: T,
        window: WindowType,
        kaiser_beta: T,
    ) -> Self {
        debug_assert!(n_taps > 0, "Number of taps must be positive");
        debug_assert!(srate > T::zero(), "Sample rate must be positive");
        debug_assert!(
            cutoff > T::zero() && cutoff < srate / lit(2.0),
            "Cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            cutoff
        );

        let coeffs = design_fir_highpass(n_taps, cutoff, srate, window, kaiser_beta);
        let n = coeffs.len();
        let symmetric = Self::coeffs_are_symmetric(&coeffs);
        Fir {
            filter_type: FirFilterType::Highpass,
            coeffs,
            srate,
            freq: cutoff,
            freq_upper: None,
            window,
            kaiser_beta,
            state: vec![T::zero(); 2 * n],
            state_pos: n,
            symmetric,
        }
    }

    /// Creates a bandpass FIR filter by multiplying two sinc functions.
    ///
    /// # Arguments
    /// * `n_taps` - Number of filter taps (must be odd)
    /// * `freq_low` - Lower cutoff frequency in Hz
    /// * `freq_high` - Upper cutoff frequency in Hz
    /// * `srate` - Sample rate in Hz
    /// * `window` - Window function to use
    /// * `kaiser_beta` - Beta parameter for Kaiser window (ignored for other windows)
    ///
    /// # Panics
    /// Panics in debug mode if:
    /// - `n_taps` is zero
    /// - `srate` is not positive
    /// - `freq_low` is not positive or >= Nyquist frequency (srate/2)
    /// - `freq_high` is not positive or >= Nyquist frequency (srate/2)
    /// - `freq_low` >= `freq_high`
    pub fn bandpass(
        n_taps: usize,
        freq_low: T,
        freq_high: T,
        srate: T,
        window: WindowType,
        kaiser_beta: T,
    ) -> Self {
        debug_assert!(n_taps > 0, "Number of taps must be positive");
        debug_assert!(srate > T::zero(), "Sample rate must be positive");
        debug_assert!(
            freq_low > T::zero() && freq_low < srate / lit(2.0),
            "Lower cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            freq_low
        );
        debug_assert!(
            freq_high > T::zero() && freq_high < srate / lit(2.0),
            "Upper cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            freq_high
        );
        debug_assert!(
            freq_low < freq_high,
            "Lower cutoff frequency ({}Hz) must be less than upper cutoff frequency ({}Hz)",
            freq_low,
            freq_high
        );

        let coeffs = design_fir_bandpass(n_taps, freq_low, freq_high, srate, window, kaiser_beta);
        let n = coeffs.len();
        let symmetric = Self::coeffs_are_symmetric(&coeffs);
        Fir {
            filter_type: FirFilterType::Bandpass,
            coeffs,
            srate,
            freq: freq_low,
            freq_upper: Some(freq_high),
            window,
            kaiser_beta,
            state: vec![T::zero(); 2 * n],
            state_pos: n,
            symmetric,
        }
    }

    /// Creates a bandstop FIR filter using spectral inversion of a bandpass filter.
    ///
    /// # Arguments
    /// * `n_taps` - Number of filter taps (must be odd)
    /// * `freq_low` - Lower cutoff frequency in Hz
    /// * `freq_high` - Upper cutoff frequency in Hz
    /// * `srate` - Sample rate in Hz
    /// * `window` - Window function to use
    /// * `kaiser_beta` - Beta parameter for Kaiser window (ignored for other windows)
    ///
    /// # Panics
    /// Panics in debug mode if:
    /// - `n_taps` is zero
    /// - `srate` is not positive
    /// - `freq_low` is not positive or >= Nyquist frequency (srate/2)
    /// - `freq_high` is not positive or >= Nyquist frequency (srate/2)
    /// - `freq_low` >= `freq_high`
    pub fn bandstop(
        n_taps: usize,
        freq_low: T,
        freq_high: T,
        srate: T,
        window: WindowType,
        kaiser_beta: T,
    ) -> Self {
        debug_assert!(n_taps > 0, "Number of taps must be positive");
        debug_assert!(srate > T::zero(), "Sample rate must be positive");
        debug_assert!(
            freq_low > T::zero() && freq_low < srate / lit(2.0),
            "Lower cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            freq_low
        );
        debug_assert!(
            freq_high > T::zero() && freq_high < srate / lit(2.0),
            "Upper cutoff frequency must be positive and below Nyquist ({}Hz), got {}Hz",
            srate / lit::<T>(2.0),
            freq_high
        );
        debug_assert!(
            freq_low < freq_high,
            "Lower cutoff frequency ({}Hz) must be less than upper cutoff frequency ({}Hz)",
            freq_low,
            freq_high
        );

        let coeffs = design_fir_bandstop(n_taps, freq_low, freq_high, srate, window, kaiser_beta);
        let n = coeffs.len();
        let symmetric = Self::coeffs_are_symmetric(&coeffs);
        Fir {
            filter_type: FirFilterType::Bandstop,
            coeffs,
            srate,
            freq: freq_low,
            freq_upper: Some(freq_high),
            window,
            kaiser_beta,
            state: vec![T::zero(); 2 * n],
            state_pos: n,
            symmetric,
        }
    }

    /// Returns the number of filter taps (coefficients).
    pub fn n_taps(&self) -> usize {
        self.coeffs.len()
    }

    /// Returns a reference to the filter coefficients.
    pub fn coeffs(&self) -> &[T] {
        &self.coeffs
    }

    /// Resets the filter state to zero.
    pub fn reset(&mut self) {
        self.state.fill(T::zero());
        self.state_pos = self.n_taps();
    }

    /// Processes a single audio sample through the filter.
    pub fn process(&mut self, x: T) -> T {
        let n_taps = self.coeffs.len();
        // Store input sample in circular buffer and its duplicate so the
        // convolution can read one contiguous slice.
        self.state[self.state_pos] = x;
        self.state[self.state_pos - n_taps] = x;

        // Compute output using convolution
        let y = if self.symmetric {
            self.compute_output_symmetric()
        } else {
            #[cfg(all(target_arch = "aarch64", target_feature = "neon"))]
            if std::mem::size_of::<T>() == 8 {
                unsafe { self.compute_output_f64_neon(self.state_pos) }
            } else {
                self.compute_output()
            }
            #[cfg(not(all(target_arch = "aarch64", target_feature = "neon")))]
            {
                self.compute_output()
            }
        };

        // Update circular buffer position (kept in the upper half of the
        // doubled state buffer).
        self.state_pos += 1;
        if self.state_pos == 2 * n_taps {
            self.state_pos = n_taps;
        }

        y
    }

    /// Processes a block of audio samples in-place.
    pub fn process_block(&mut self, samples: &mut [T]) {
        if self.symmetric {
            self.process_block_symmetric(samples);
        } else {
            self.process_block_general(samples);
        }
    }

    fn process_block_general(&mut self, samples: &mut [T]) {
        let n_taps = self.coeffs.len();

        for sample in samples.iter_mut() {
            let x = *sample;
            // Store input sample in circular buffer and its duplicate
            self.state[self.state_pos] = x;
            self.state[self.state_pos - n_taps] = x;

            // Compute output using convolution
            *sample = self.compute_output();

            // Update circular buffer position
            self.state_pos += 1;
            if self.state_pos == 2 * n_taps {
                self.state_pos = n_taps;
            }
        }
    }

    fn process_block_symmetric(&mut self, samples: &mut [T]) {
        let n_taps = self.coeffs.len();

        for sample in samples.iter_mut() {
            let x = *sample;
            // Store input sample in circular buffer and its duplicate
            self.state[self.state_pos] = x;
            self.state[self.state_pos - n_taps] = x;

            // Compute output using convolution
            *sample = self.compute_output_symmetric();

            // Update circular buffer position
            self.state_pos += 1;
            if self.state_pos == 2 * n_taps {
                self.state_pos = n_taps;
            }
        }
    }

    #[inline(always)]
    fn compute_output(&self) -> T {
        let state_pos = self.state_pos;
        let n_taps = self.coeffs.len();
        let start = state_pos - n_taps + 1;

        // The newest sample is at `state_pos`, the oldest at `start`.
        // Coeffs[0] multiplies the newest, so one slice is reversed.
        self.coeffs
            .iter()
            .zip(self.state[start..=state_pos].iter().rev())
            .map(|(&c, &s)| c * s)
            .sum()
    }

    /// aarch64 NEON fast path for a single general (non-symmetric) output
    /// sample when `T` is `f64`.
    ///
    /// # Safety
    /// Must only be called when `T` is `f64` (checked by the caller via
    /// `size_of::<T>() == 8`).
    #[cfg(all(target_arch = "aarch64", target_feature = "neon"))]
    #[inline(always)]
    unsafe fn compute_output_f64_neon(&self, state_pos: usize) -> T {
        // SAFETY: caller verified `T` is `f64`. All pointer accesses are within
        // the `coeffs`/`state` slices, and NEON is available on this target.
        unsafe {
            use std::arch::aarch64::*;

            let coeffs_ptr = self.coeffs.as_ptr() as *const f64;
            let state_ptr = self.state.as_ptr() as *const f64;
            let n_taps = self.coeffs.len();

            let mut acc0 = vdupq_n_f64(0.0);
            let mut acc1 = vdupq_n_f64(0.0);
            let mut i = 0;
            while i + 3 < n_taps {
                let c0 = vld1q_f64(coeffs_ptr.add(i));
                let s0_raw = vld1q_f64(state_ptr.add(state_pos - i - 1));
                let s0 = vextq_f64(s0_raw, s0_raw, 1);
                acc0 = vfmaq_f64(acc0, c0, s0);

                let c1 = vld1q_f64(coeffs_ptr.add(i + 2));
                let s1_raw = vld1q_f64(state_ptr.add(state_pos - i - 3));
                let s1 = vextq_f64(s1_raw, s1_raw, 1);
                acc1 = vfmaq_f64(acc1, c1, s1);

                i += 4;
            }
            let mut acc = vaddq_f64(acc0, acc1);

            while i + 1 < n_taps {
                let c = vld1q_f64(coeffs_ptr.add(i));
                let s_raw = vld1q_f64(state_ptr.add(state_pos - i - 1));
                let s = vextq_f64(s_raw, s_raw, 1);
                acc = vfmaq_f64(acc, c, s);
                i += 2;
            }
            let mut y = vgetq_lane_f64(acc, 0) + vgetq_lane_f64(acc, 1);

            while i < n_taps {
                y = (*coeffs_ptr.add(i)).mul_add(*state_ptr.add(state_pos - i), y);
                i += 1;
            }

            std::mem::transmute_copy::<f64, T>(&y)
        }
    }

    /// Computes one output sample exploiting symmetric coefficients.
    ///
    /// For a symmetric filter `h[i] == h[n_taps-1-i]` the convolution reduces to
    /// roughly half the multiplies: each coefficient pairs the newest and oldest
    /// samples in the current window.
    #[inline(always)]
    fn compute_output_symmetric(&self) -> T {
        let state_pos = self.state_pos;
        let n_taps = self.coeffs.len();
        let start = state_pos - n_taps + 1;
        let half = n_taps / 2;

        // On aarch64 use NEON FMA to keep the symmetric dot product in vector
        // registers (one rounding, one instruction per pair). FilterFloat is only
        // implemented for f32/f64, so size == 8 identifies f64 at runtime.
        #[cfg(all(target_arch = "aarch64", target_feature = "neon"))]
        if std::mem::size_of::<T>() == 8 {
            return unsafe { self.compute_output_symmetric_f64(state_pos, start, half) };
        }

        // Pair the oldest and newest samples in the window; for symmetric
        // coefficients each pair shares one coefficient, halving the multiplies.
        let pair_sums = self.state[start..start + half]
            .iter()
            .zip(self.state[state_pos - half + 1..=state_pos].iter().rev())
            .map(|(&old, &new)| old + new);
        let mut y: T = self.coeffs[..half].iter().zip(pair_sums).map(|(&c, s)| c * s).sum();
        if n_taps % 2 == 1 {
            y += self.coeffs[half] * self.state[start + half];
        }
        y
    }

    /// aarch64 NEON fast path for [`compute_output_symmetric`] when `T` is `f64`.
    ///
    /// # Safety
    /// Must only be called when `T` is `f64` (checked by the caller via
    /// `size_of::<T>() == 8`).
    #[cfg(all(target_arch = "aarch64", target_feature = "neon"))]
    #[inline(always)]
    unsafe fn compute_output_symmetric_f64(
        &self,
        state_pos: usize,
        start: usize,
        half: usize,
    ) -> T {
        // SAFETY: caller verified `T` is `f64`. All pointer accesses are within
        // the `coeffs`/`state` slices, and NEON is available on this target.
        unsafe {
            use std::arch::aarch64::*;

            let coeffs_ptr = self.coeffs.as_ptr() as *const f64;
            let state_ptr = self.state.as_ptr() as *const f64;

            // Use two independent vector accumulators and unroll by 4 pairs
            // per iteration to keep the NEON FMA pipeline full on cores with
            // multi-cycle FMA latency. Load consecutive coefficient/old-state
            // pairs with x2 loads to reduce load-unit pressure.
            let mut acc0 = vdupq_n_f64(0.0);
            let mut acc1 = vdupq_n_f64(0.0);
            let mut i = 0;
            while i + 3 < half {
                let c = vld1q_f64_x2(coeffs_ptr.add(i));
                let old = vld1q_f64_x2(state_ptr.add(start + i));
                let new0 = vld1q_f64(state_ptr.add(state_pos - i - 1));
                let new1 = vld1q_f64(state_ptr.add(state_pos - i - 3));
                let pair0 = vaddq_f64(old.0, vextq_f64(new0, new0, 1));
                let pair1 = vaddq_f64(old.1, vextq_f64(new1, new1, 1));
                acc0 = vfmaq_f64(acc0, c.0, pair0);
                acc1 = vfmaq_f64(acc1, c.1, pair1);
                i += 4;
            }
            let mut acc = vaddq_f64(acc0, acc1);

            // Vector tail: process the remaining pair (if any) with a single
            // accumulator so the scalar loop only handles the last odd pair.
            while i + 1 < half {
                let c = vld1q_f64(coeffs_ptr.add(i));
                let old = vld1q_f64(state_ptr.add(start + i));
                let new = vld1q_f64(state_ptr.add(state_pos - i - 1));
                let pair = vaddq_f64(old, vextq_f64(new, new, 1));
                acc = vfmaq_f64(acc, c, pair);
                i += 2;
            }
            let mut y = vgetq_lane_f64(acc, 0) + vgetq_lane_f64(acc, 1);

            // Scalar tail for the final pair (kept as `mul_add` for one rounding).
            while i < half {
                let pair = *state_ptr.add(start + i) + *state_ptr.add(state_pos - i);
                y = (*coeffs_ptr.add(i)).mul_add(pair, y);
                i += 1;
            }
            let n_taps = self.coeffs.len();
            if n_taps % 2 == 1 {
                let c = *coeffs_ptr.add(half);
                let s = *state_ptr.add(start + half);
                y = c.mul_add(s, y);
            }
            // Caller guarantees T is f64, so the sizes match.
            std::mem::transmute_copy::<f64, T>(&y)
        }
    }

    /// Returns true if the coefficient vector is symmetric (within floating-point
    /// rounding tolerance). The windowed-sinc designs are mathematically symmetric
    /// but can differ by a few ULPs after normalization, so exact equality is too
    /// strict.
    fn coeffs_are_symmetric(coeffs: &[T]) -> bool {
        let n = coeffs.len();
        let eps = T::epsilon();
        for i in 0..n / 2 {
            let a = coeffs[i];
            let b = coeffs[n - 1 - i];
            let scale = a.abs().max(b.abs()).max(T::one());
            if (a - b).abs() > eps * scale {
                return false;
            }
        }
        true
    }

    /// Calculates the filter's magnitude response at a single frequency `f`.
    pub fn result(&self, f: T) -> T {
        let two_pi: T = lit::<T>(2.0) * T::PI();
        let omega = two_pi * f / self.srate;
        let mut real = T::zero();
        let mut imag = T::zero();

        for (n, &coeff) in self.coeffs.iter().enumerate() {
            let phase = -(lit::<T>(n as f64)) * omega;
            real += coeff * phase.cos();
            imag += coeff * phase.sin();
        }

        (real * real + imag * imag).sqrt()
    }

    /// Calculates the filter's response in dB at a single frequency `f`.
    pub fn log_result(&self, f: T) -> T {
        let result = self.result(f);
        if result > T::zero() {
            lit::<T>(20.0) * result.log10()
        } else {
            lit(-200.0)
        }
    }

    /// Vectorized version to compute the SPL response for a vector of frequencies.
    ///
    /// # Performance
    /// This implementation avoids per-tap allocations by using a direct nested loop.
    pub fn np_log_result(&self, freq: &Array1<T>) -> Array1<T> {
        let n_freqs = freq.len();
        let two_pi: T = lit::<T>(2.0) * T::PI();
        let omega_base = two_pi / self.srate;

        let mut real: Array1<T> = Array1::zeros(n_freqs);
        let mut imag: Array1<T> = Array1::zeros(n_freqs);

        for (n, &coeff) in self.coeffs.iter().enumerate() {
            let n_f: T = -(lit::<T>(n as f64));
            for i in 0..n_freqs {
                let phase = n_f * freq[i] * omega_base;
                real[i] += coeff * phase.cos();
                imag[i] += coeff * phase.sin();
            }
        }

        // Compute magnitude and convert to dB
        let mut magnitude = Array1::zeros(n_freqs);
        let min_val: T = lit(1.0e-20);

        for i in 0..n_freqs {
            let mag_sq = real[i] * real[i] + imag[i] * imag[i];
            let mag = mag_sq.sqrt().max(min_val);
            magnitude[i] = lit::<T>(20.0) * mag.log10();
        }

        magnitude
    }
}

impl<T: FilterFloat> fmt::Display for Fir<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.filter_type {
            FirFilterType::Bandpass | FirFilterType::Bandstop => {
                write!(
                    f,
                    "Type:{},Freq:{:.1}-{:.1},Rate:{:.1},Taps:{},Window:{}",
                    self.filter_type.short_name(),
                    self.freq.to_f64().unwrap_or(0.0),
                    self.freq_upper.unwrap_or(T::zero()).to_f64().unwrap_or(0.0),
                    self.srate.to_f64().unwrap_or(0.0),
                    self.n_taps(),
                    self.window.short_name()
                )
            }
            _ => {
                write!(
                    f,
                    "Type:{},Freq:{:.1},Rate:{:.1},Taps:{},Window:{}",
                    self.filter_type.short_name(),
                    self.freq.to_f64().unwrap_or(0.0),
                    self.srate.to_f64().unwrap_or(0.0),
                    self.n_taps(),
                    self.window.short_name()
                )
            }
        }
    }
}

/// Compute the FIR bank SPL response at given frequencies.
pub fn fir_bank_spl<T: FilterFloat>(freq: &Array1<T>, fir_bank: &FirBank<T>) -> Array1<T> {
    compute_fir_bank_response(freq, fir_bank)
}

/// Calculate the recommended preamp gain to avoid clipping for a FIR bank.
///
/// This computes the maximum gain across the audible frequency range
/// and returns the negative of that value.
pub fn fir_bank_preamp_gain<T: FilterFloat>(fir_bank: &FirBank<T>) -> T {
    if fir_bank.is_empty() {
        return T::zero();
    }

    // Sample frequencies across the audible range
    let freqs = Array1::logspace(
        lit(10.0),
        lit::<T>(20.0_f64).log10(),
        lit::<T>(20000.0_f64).log10(),
        500,
    );
    let response = fir_bank_spl(&freqs, fir_bank);

    // Find maximum gain
    let max_gain = response
        .iter()
        .copied()
        .fold(T::neg_infinity(), |a, b| a.max(b));

    // Return negative of max gain (to reduce overall level)
    -max_gain
}
